import Database from 'better-sqlite3';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DB_PATH = path.join(__dirname, '../agent.db');

const db = new Database(DB_PATH);

const args = process.argv.slice(2);
const scenarioId = args[0];

if (!scenarioId) {
  console.error('Please provide a scenario ID.');
  console.error('Usage: npm run db:scenario <ID>');
  process.exit(1);
}

function showScenarioArtifacts(id: number) {
  // 1. Get Scenario Info
  const scenario = db.prepare('SELECT * FROM scenarios WHERE id = ?').get(id) as any;
  if (!scenario) {
    console.error(`Scenario ID ${id} not found.`);
    return;
  }

  console.log(`\n==================================================`);
  console.log(` SCENARIO [ID: ${id}]`);
  console.log(`==================================================`);
  console.log(`Concept: ${scenario.concept}`);
  console.log(`Created: ${scenario.created_at}`);
  
  const metadata = JSON.parse(scenario.metadata);
  console.log(`Category: ${metadata.category} / Type: ${metadata.structureType}`);
  console.log(`Theme: ${metadata.theme || "N/A"}`); // Assuming theme is stored in metadata if available

  // 2. Get Artifact Logs to find real IDs?
  // Actually, the prompt asks to show "actual Item, User created along the scenario".
  // The 'scenarios' table stores metadata and concept.
  // The 'artifact_logs' stores the mapping from tempId -> realId.
  // BUT, where is the CONTENT of the generated users/items stored?
  // Currently, the content is sent to Backend via MCP and stored in Postgres.
  // Agent DB ONLY stores the ID mapping and the Scenario Concept.
  // The Agent DB DOES NOT store the full JSON of generated users/items.
  
  // So, to show "actual Item, User", we have two options:
  // A. Fetch them from the Production DB (Postgres) using the real_id from artifact_logs.
  // B. Or maybe the user implies seeing the "plan" (the JSON generated by Scenarist)?
  //    But we don't save the full JSON in Agent DB currently. We only save metadata.
  
  // Checking `src/nodes/saver.ts`:
  // We send `cluster` to MCP.
  // We save `metadata` to Agent DB: { category, structureType, userCount, itemCount }
  // We DO NOT save the full cluster JSON to Agent DB.
  
  // Therefore, we can ONLY show the ID mappings unless we query the Backend DB.
  // Since we are "Agent", we shouldn't directly touch Backend DB (rule).
  // But for a debug script, maybe it's allowed? Or maybe we can't.
  
  // Let's first show what we have in Agent DB (Logs).
  // If the user wants to see the content, we might need to modify Saver to store the full JSON 
  // in Agent DB (e.g. in a new 'content' column or 'metadata'), OR query Postgres.
  
  // Given the current architecture, I will show the Artifact Logs (ID mappings).
  // If the user wants to see names/bios, we might need to enhance the Saver to store that info 
  // or query the backend.
  
  // Let's check `artifact_logs`.
  const logs = db.prepare('SELECT temp_id, real_id FROM artifact_logs WHERE scenario_id = ?').all(id) as any[];

  if (logs.length === 0) {
    console.log('\nNo artifacts found for this scenario.');
    return;
  }

  // Group by type based on temp_id prefix (convention: u_..., p_..., i_...)
  const users = logs.filter(l => l.temp_id.startsWith('u_'));
  const projects = logs.filter(l => l.temp_id.startsWith('p_'));
  const items = logs.filter(l => l.temp_id.startsWith('i_'));
  const others = logs.filter(l => !l.temp_id.startsWith('u_') && !l.temp_id.startsWith('p_') && !l.temp_id.startsWith('i_'));

  console.log(`\n--- Generated Artifacts (${logs.length} total) ---`);
  
  if (users.length > 0) {
    console.log(`\n[Users: ${users.length}]`);
    console.table(users.map(u => ({ 'Temp ID': u.temp_id, 'Real ID (in Prod DB)': u.real_id })));
  }

  if (projects.length > 0) {
    console.log(`\n[Projects: ${projects.length}]`);
    console.table(projects.map(p => ({ 'Temp ID': p.temp_id, 'Real ID (in Prod DB)': p.real_id })));
  }

  if (items.length > 0) {
    console.log(`\n[Items: ${items.length}]`);
    console.table(items.map(i => ({ 'Temp ID': i.temp_id, 'Real ID (in Prod DB)': i.real_id })));
  }
  
  if (others.length > 0) {
    console.log(`\n[Others: ${others.length}]`);
    console.table(others);
  }

  console.log(`\nNOTE: Content details (Name, Bio, etc.) are stored in the Production DB (PostgreSQL).`);
  console.log(`      Agent DB only tracks the lineage (ID mapping).`);
}

showScenarioArtifacts(Number(scenarioId));
