
import { McpClient } from '../src/utils/mcp-client.js';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

// Load agent env
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.join(__dirname, '../.env') });

async function main() {
  console.log("Testing McpClient...");

  // Dummy Data
  const dummyCluster = {
    users: [
      {
        tempId: "temp_user_4",
        publicId: "user_test_004",
        name: "Test User D",
        role: "BUYER"
      }
    ],
    projects: [
      {
        tempId: "temp_proj_4",
        publicId: "proj_test_004",
        ownerId: "temp_user_4",
        name: "Test Project D",
        description: "This is a test project generated by MCP client test v4 with BlockNote content.",
        mode: "INDIVIDUAL",
        memberIds: ["temp_user_4"]
      }
    ],
    items: [
      {
        tempId: "temp_item_4",
        publicId: "item_test_004",
        authorId: "temp_user_4",
        projectId: "temp_proj_4",
        name: "Test Item D",
        description: "This is a test item v4 with BlockNote content."
      }
    ]
  };

  try {
    const result = await McpClient.saveScenarioCluster(dummyCluster);
    console.log("Result:", JSON.stringify(result, null, 2));
  } catch (error) {
    console.error("Test Failed:", error);
  }
}

main();
