% $latex = 'platex';
% $bibtex = 'pbibtex';
% $dvipdf = 'dvipdfmx %O -o %D %S';
% $makeindex = 'mendex %O -o %D %S';
% $pdf_mode = 3; 

$latex = 'uplatex';
$bibtex = 'biber';
$dvipdf = 'dvipdfmx %O -o %D %S';
$makeindex = 'mendex -U %O -o %D %S';
$pdf_mode = 3; 